### ISSUE TITLE
Let it play HATERIS

### ISSUE THREAD

**Issue by Kaligule** [Code-Bullet/Tetris-AI-Javascript#4]
[Hatetris](https://qntm.org/files/hatetris/hatetris.html) is like tetris - only it always gives you the worst piece possible.
It gives tetris an amazing spin.

Hateris is open source (repo linked in the game) and also written in javascript so it should not be too hard to wire into the tetris-AI.

**Comment by J-Cake** [comment]
FUCK YEA

**Comment by Seppel3210** [comment]
No. That game is boring because it is impossible to play indefinitely.

**Comment by Kaligule** [comment]
@Seppel3210 Do you have anything to support that claim? Its news to me.

**Comment by CoolCat467** [comment]
This is not an issue. This is a pull request.

**Comment by analog-hors** [comment]
https://harddrop.com/wiki/A_deadly_piece_sequence
