### ISSUE TITLE
play yourself / lower the population of generic AI

### ISSUE THREAD

**Issue by ghost** [Code-Bullet/Tetris-AI-Javascript#7]
how do you play  yourself or lower the population of generic AI ?

**Comment by CoolCat467** [comment]
To play a regular game without the AI, do the following:
In "sketch.js", in the function "setup", uncomment the line that says "game = new Game(gameWidthBlocks, gameHeightBlocks);" and comment out the line above it about making the population object, and then in the "draw" function, comment out the lines after the "push" statement up to where it is commented out currently, and then uncomment everything in that function that was previously commented out. There isn't an easy way except modifying the code as described above.

To lower the population of the AI:
In "sketch.js", up close to the top (at this moment in time it is line number 28), change the value that the variable "populationSize" to your desired population size.

**Comment by CoolCat467** [comment]
Once you look at the code it's pretty simple to figure out, and you can get the gist of it by the comments and variable names even if you don't know how to program.

**Comment by ghost** [comment]
Thanks

**Comment by CoolCat467** [comment]
@ashkan1234567 Issue can be closed now
